#!/usr/bin/env python3



FILE_TAG='SourceFile'

FILE_FIELD="#File"
SOURCE_FIELD="#Source"
SOFTWARE_FIELD="#Software"
CREATOR_FIELD="#Creator"
CONTRIBUTORS_FIELD="#Contributors"
OWNER_FIELD="#Owner"
CONTACT_URL_FIELD="#ContactURL"
DATE_FIELD="#date"
RIGHTS_FIELD="#Rights"
RIGHTS_URL_FIELD="#RightsURL"


METADATA={}
METADATA[FILE_FIELD]=''
METADATA[SOURCE_FIELD]=''
METADATA[SOFTWARE_FIELD]=''
METADATA[CREATOR_FIELD]=''
METADATA[CONTRIBUTORS_FIELD]=''
METADATA[OWNER_FIELD]=''
METADATA[CONTACT_URL_FIELD]=''
METADATA[DATE_FIELD]=''
METADATA[RIGHTS_FIELD]=''
METADATA[RIGHTS_URL_FIELD]=''

